# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-07 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localvlans',
            name='vlan_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='remotevlans',
            name='vlan_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tmp',
            name='vlan_id',
            field=models.IntegerField(default=1),
        ),
    ]
